let age=20;
console.log(age);
console.log('2'/'2');
let age1=20;
age1=String(age1);
console.log(typeof age1);
let isadult=true;
isadult=String(isadult);
console.log(isadult);
let age2="23";
age2=Number(age2);
console.log(typeof age2);
let age3='true';
age3=Number(age3);
console.log(typeof age3);
console.log(age3);
let age4=true;
console.log( age4);
let age5="null";
console.log(typeof age5);
let age6=null;
console.log(age6);
