    let age=23;
      age =String(age);
      console.log(age);
      console.log(typeof age);
      let bool=true;
      bool=String(bool);
      console.log(bool);
      console.log(typeof bool);
      let age1='29';
      age1=Number(age1);
      console.log(age1+3);
      console.log(typeof age1);
      let age2='true';
      age2=Number(age2);
      console.log(age2);
      console.log(typeof age2);
      let age3=undefined;
      age3=Number(age3);
      console.log(typeof age3);
      console.log(age3);
      let x=1;
      console.log(typeof x);
      x=Boolean(x);
      console.log(typeof x);
      console.log(x);
