let a=10;
let b=20;
console.log(a<b);
console.log(a>b);
console.log(a<=b);
console.log(a>=b);
console.log(a==b);
console.log(a!=b);
let x="dhivya";
let y="dharshini";
console.log(x<y);
console.log(x>y);
let a1="2";
let a2=1;
console.log(a1<a2);
let a3=false;
let a4=1;
console.log(a3==a4);
console.log(null>0);
console.log(null<=0);
console.log(null<0);
console.log(null==0);
console.log(undefined>0);
console.log( undefined<=0);
console.log(Number(undefined));  
