let pi=3.14;
let prime=29;
console.log(pi,"\n", prime);
let infi=Infinity;
let neginfi=-Infinity;
let nan=NaN;
let sum=543+235;
console.log(typeof sum);
console.log(infi);
console.log(neginfi);
console.log(typeof infi);
console.log(typeof nan); 
let limit=9007992547991n;
console.log(limit+1n);
console.log(limit+2n);
console.log(typeof limit);
let largerNumber=12345678910n;
console.log(largerNumber+2024n);
let intro="hi i am dhivyadharshini";
console.log(intro);
let pay="this is dhivya book's";
console.log(pay);
let quote='me said"i am strong girls"';
console.log(quote);
let para=`this is dhivya  book's."bruce way"`;
console.log(para);
let embed=`1+2=${1+2}`;
console.log(embed);
